# Generated by Django 5.0.7 on 2024-07-24 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("allDay", models.BooleanField(default=False)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("behavior", "Behavior"),
                            ("diseases", "Diseases"),
                            ("enrichment", "Enrichment"),
                            ("care", "Care"),
                            ("grooming", "Grooming"),
                            ("nutrition", "Nutrition"),
                            ("vaccination", "Vaccination"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CatProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("gender", models.CharField(blank=True, max_length=50, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("breed", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "microchip_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="photos/"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("time", models.TimeField(blank=True, null=True)),
                ("portion_size", models.FloatField(blank=True, null=True)),
                ("food_brand", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "cat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="health.catprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HairballRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("method", models.CharField(blank=True, max_length=100, null=True)),
                ("vomited", models.BooleanField(default=False)),
                (
                    "cat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="health.catprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HealthRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.FloatField(blank=True, null=True)),
                ("last_vaccination", models.DateField(blank=True, null=True)),
                ("last_antiparasitic", models.DateField(blank=True, null=True)),
                ("last_vet_appointment", models.DateField(blank=True, null=True)),
                ("flea_tick_prevention", models.DateField(blank=True, null=True)),
                ("deworming_treatment", models.DateField(blank=True, null=True)),
                ("medication_records", models.TextField(blank=True, null=True)),
                ("vet_visit_details", models.TextField(blank=True, null=True)),
                ("warning_signs", models.TextField(blank=True, null=True)),
                ("diet", models.TextField(blank=True, null=True)),
                ("exercise_routine", models.JSONField(blank=True, null=True)),
                ("grooming_schedule", models.JSONField(blank=True, null=True)),
                ("teeth_cleaning", models.JSONField(blank=True, null=True)),
                ("hairball_prevention", models.JSONField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "cat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="health.catprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InteractionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("played", models.BooleanField(default=False)),
                ("sleep_quality", models.IntegerField(blank=True, null=True)),
                (
                    "cat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="health.catprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recommendation_type", models.CharField(max_length=50)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("done", "Done"),
                            ("not_applicable", "Not Applicable"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "cat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="health.catprofile",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="health.resource",
                    ),
                ),
            ],
        ),
    ]
